name = "barber-api"
main = "worker/index.ts"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]
account_id = "64bf5b1d5ff3666393840bd39c39c9dd"

[vars]
JWT_SECRET = "super-secret-jwt-key-for-barber-app-2024-change-me"
FRONTEND_URL = "https://barber-booking-app.pages.dev"

[[d1_databases]]
binding = "barber_db"
database_name = "barber-db"
database_id = "649bf835-a610-414d-91e4-e12e4118620e"

[env.development]
bindings = []

[env.production]
bindings = []